[2025-03-29 10:19:05,659: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 10:19:05,661: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 10:19:05,661: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 10:19:05,670: INFO: common: created directory at: artifacts]
[2025-03-29 10:19:05,672: INFO: common: created directory at: artifacts/data_validation]
[2025-03-29 10:26:39,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 10:26:39,377: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 10:26:39,389: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 10:26:39,389: INFO: common: created directory at: artifacts]
[2025-03-29 10:26:39,392: INFO: common: created directory at: artifacts/data_validation]
[2025-03-29 10:28:02,078: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 10:28:02,079: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 10:28:02,082: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 10:28:02,083: INFO: common: created directory at: artifacts]
[2025-03-29 10:28:02,084: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-29 10:28:03,773: INFO: 3447005916: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21984
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "85a38be3d4c70e3b6dc97fc47873623da88c9b850e1526aeb57ff236bdd2815c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 31CC:205558:7BC12:1A2997:67E77DDD
Accept-Ranges: bytes
Date: Sat, 29 Mar 2025 04:58:06 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100021-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1743224286.813436,VS0,VE280
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9553bbd82ad53fc55fbb919009e60dbfdda2a11a
Expires: Sat, 29 Mar 2025 05:03:06 GMT
Source-Age: 0

]
[2025-03-29 10:28:15,860: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 10:28:15,862: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 10:28:15,865: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 10:28:15,867: INFO: common: created directory at: artifacts]
[2025-03-29 10:28:15,867: INFO: common: created directory at: artifacts/data_validation]
[2025-03-29 10:29:33,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 10:29:33,154: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 10:29:33,154: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 10:29:33,154: INFO: common: created directory at: artifacts]
[2025-03-29 10:29:33,154: INFO: common: created directory at: artifacts/data_validation]
[2025-03-29 10:41:39,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 10:41:39,091: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 10:41:39,096: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 10:41:39,096: INFO: common: created directory at: artifacts]
[2025-03-29 10:43:11,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 10:43:11,256: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 10:43:11,268: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 10:43:11,270: INFO: common: created directory at: artifacts]
[2025-03-29 10:43:11,272: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-29 10:43:11,323: INFO: 40091733: Splited data into training and test sets]
[2025-03-29 10:43:11,324: INFO: 40091733: (857, 13)]
[2025-03-29 10:43:11,327: INFO: 40091733: (286, 13)]
[2025-03-29 16:20:02,941: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 16:20:02,945: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 16:20:02,950: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 16:20:02,950: INFO: common: created directory at: artifacts]
[2025-03-29 16:37:43,772: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 16:37:43,775: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 16:37:43,777: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 16:37:43,778: INFO: common: created directory at: artifacts]
[2025-03-29 16:40:02,182: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 16:40:02,199: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 16:40:02,200: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 16:40:02,200: INFO: common: created directory at: artifacts]
[2025-03-29 16:42:43,931: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 16:42:43,932: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 16:42:43,937: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 16:42:43,937: INFO: common: created directory at: artifacts]
[2025-03-29 16:42:43,937: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-29 20:21:06,354: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 20:21:06,358: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 20:21:06,361: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 20:21:06,364: INFO: common: created directory at: artifacts]
[2025-03-29 20:21:06,364: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-29 21:43:58,896: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 21:43:58,900: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 21:43:58,900: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 21:43:58,900: INFO: common: created directory at: artifacts]
[2025-03-29 21:43:58,900: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-29 21:43:59,012: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-03-29 21:57:29,306: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-29 21:57:29,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 21:57:29,320: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 21:57:29,320: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 21:57:29,320: INFO: common: created directory at: artifacts]
[2025-03-29 21:57:29,325: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-29 21:57:31,256: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21984
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "85a38be3d4c70e3b6dc97fc47873623da88c9b850e1526aeb57ff236bdd2815c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 156F:1FDFDA:266E1A:65C99E:67E81F74
Accept-Ranges: bytes
Date: Sat, 29 Mar 2025 16:27:35 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100028-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1743265655.777887,VS0,VE283
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 799a0367872f864f2e7db036ea1f851c7a256609
Expires: Sat, 29 Mar 2025 16:32:35 GMT
Source-Age: 0

]
[2025-03-29 21:57:31,266: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-29 21:57:31,266: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-29 21:57:31,269: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-29 21:57:31,269: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-29 21:57:31,277: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-29 21:57:31,277: INFO: common: created directory at: artifacts]
[2025-03-29 21:57:31,279: INFO: common: created directory at: artifacts/data_validation]
[2025-03-29 21:57:31,280: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_ingestion/winequality-red.csv']
Traceback (most recent call last):
  File "c:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\main.py", line 26, in <module>
    data_ingestion.main()
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\pipeline\stage_02_data_validation.py", line 16, in main
    data_validation.validate_all_columns()
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\components\data_validation.py", line 36, in validate_all_columns
    raise e
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\components\data_validation.py", line 17, in validate_all_columns
    data = pd.read_csv(self.config.unzip_data_dir)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_ingestion/winequality-red.csv'
[2025-03-30 12:17:15,473: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-30 12:17:15,473: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-30 12:17:15,473: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-30 12:17:15,488: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-30 12:17:15,488: INFO: common: created directory at: artifacts]
[2025-03-30 12:17:15,488: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-30 12:17:17,622: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21314
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "6bf518658e1398638afccf51fcd1c3bf795ad8b440f51243d26409da9095884c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 433E:27BDDD:A8BAF:2118E5:67E8E8F3
Accept-Ranges: bytes
Date: Sun, 30 Mar 2025 06:47:21 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100035-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1743317241.821112,VS0,VE262
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: bb91118d8b9d1c2a2fabbc902b75dce5f7d53776
Expires: Sun, 30 Mar 2025 06:52:21 GMT
Source-Age: 0

]
[2025-03-30 12:17:17,640: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-30 12:17:17,640: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-30 12:17:17,658: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-30 12:17:17,661: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-30 12:17:17,661: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-30 12:17:17,669: INFO: common: created directory at: artifacts]
[2025-03-30 12:17:17,672: INFO: common: created directory at: artifacts/data_validation]
[2025-03-30 12:17:17,687: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-30 12:17:17,701: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-30 12:17:17,703: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-30 12:17:17,704: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-30 12:17:17,704: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-30 12:17:17,704: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-30 12:17:17,717: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-30 12:17:17,718: INFO: common: created directory at: artifacts]
[2025-03-30 12:17:17,720: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-30 12:17:17,720: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_transformation/train.csv']
Traceback (most recent call last):
  File "c:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\main.py", line 50, in <module>
    data_ingestion.main()
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\pipeline\stage_04_model_trainer.py", line 17, in main
    model_trainer_config.train()
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\components\model_trainer.py", line 15, in train
    train_data = pd.read_csv(self.config.train_data_path)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_transformation/train.csv'
[2025-03-30 12:56:59,118: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-30 12:56:59,128: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-30 12:56:59,128: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-30 12:56:59,128: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-30 12:56:59,128: INFO: common: created directory at: artifacts]
[2025-03-30 12:56:59,128: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-30 12:57:00,961: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 21314
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "6bf518658e1398638afccf51fcd1c3bf795ad8b440f51243d26409da9095884c"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 433E:27BDDD:A8BAF:2118E5:67E8E8F3
Accept-Ranges: bytes
Date: Sun, 30 Mar 2025 07:27:04 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100033-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1743319624.241125,VS0,VE265
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 18e7270f68726bc0abaee6e89770a4961373ea75
Expires: Sun, 30 Mar 2025 07:32:04 GMT
Source-Age: 0

]
[2025-03-30 12:57:00,971: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-30 12:57:00,971: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-30 12:57:00,974: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-30 12:57:00,974: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-30 12:57:00,980: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-30 12:57:00,980: INFO: common: created directory at: artifacts]
[2025-03-30 12:57:00,980: INFO: common: created directory at: artifacts/data_validation]
[2025-03-30 12:57:00,996: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-30 12:57:01,004: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-30 12:57:01,043: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-30 12:57:01,043: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-30 12:57:01,052: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-30 12:57:01,052: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-30 12:57:01,052: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-30 12:57:01,052: INFO: common: created directory at: artifacts]
[2025-03-30 12:57:01,052: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-30 12:57:01,052: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_transformation/train.csv']
Traceback (most recent call last):
  File "c:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\main.py", line 50, in <module>
    data_ingestion.main()
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\pipeline\stage_04_model_trainer.py", line 17, in main
    model_trainer_config.train()
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\components\model_trainer.py", line 15, in train
    train_data = pd.read_csv(self.config.train_data_path)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "C:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\.venv\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_transformation/train.csv'
[2025-03-30 13:27:14,333: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-30 13:27:14,335: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-30 13:27:14,336: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-30 13:27:14,338: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-30 13:27:14,338: INFO: common: created directory at: artifacts]
[2025-03-30 13:27:14,339: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-30 13:27:14,339: INFO: data_ingestion: File already exists of size: ~ 21 KB]
[2025-03-30 13:27:14,341: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-30 13:27:14,342: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-30 13:27:14,343: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-30 13:27:14,343: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-30 13:27:14,349: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-30 13:27:14,349: INFO: common: created directory at: artifacts]
[2025-03-30 13:27:14,350: INFO: common: created directory at: artifacts/data_validation]
[2025-03-30 13:27:14,361: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-30 13:27:14,361: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-30 13:27:14,362: ERROR: main: Your data schema is not valid]
Traceback (most recent call last):
  File "c:\Users\LENOVO\OneDrive\Computer Engineering\Programming\Machine Learning\ml-end-to-end\main.py", line 38, in <module>
    data_ingestion.main()
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\pipeline\stage_03_data_transformation.py", line 30, in main
    raise e
  File "c:\users\lenovo\onedrive\computer engineering\programming\machine learning\ml-end-to-end\src\mlProject\pipeline\stage_03_data_transformation.py", line 26, in main
    raise Exception("Your data schema is not valid")
Exception: Your data schema is not valid
